"""db model updated for razorpay

Revision ID: bd87a116edce
Revises: 425f84f2aff7
Create Date: 2026-03-06 06:08:40.456561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd87a116edce'
down_revision: Union[str, Sequence[str], None] = '425f84f2aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_gateway', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.alter_column('transactions', 'stripe_session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_transactions_payment_gateway'), 'transactions', ['payment_gateway'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_transactions_razorpay_payment_id'), 'transactions', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_razorpay_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_gateway'), table_name='transactions')
    op.alter_column('transactions', 'stripe_session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('transactions', 'razorpay_payment_id')
    op.drop_column('transactions', 'razorpay_order_id')
    op.drop_column('transactions', 'payment_gateway')
    # ### end Alembic commands ###
